#!/bin/bash

set -e

# Parse image name for repo name
tagStart=$(expr index "$IMAGE_NAME" :)  
repoName=${IMAGE_NAME:0:tagStart-1}

# Tag and push image for each additional tag
#for tag in "php7-xdebug php7-test"; do  
    docker tag $IMAGE_NAME ${repoName}:php7-xdebug
    docker push ${repoName}:${tag}
#done  
